name: contrast-phys
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - gcc_linux-64=8
  - gxx_linux-64=8
  - opencv
  - dlib
  - pip:
    - h5py==3.6.0
    - matplotlib==3.5.1
    - numpy==1.21.5
    - opencv-python==4.5.4.58
    - sacred==0.8.2
    - scipy==1.8.0
    - torch==1.11.0+cu113
    - pandas==1.1.4
    - gdown
